language: cpp
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - g++-5
      - gcc-5

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install cmake; fi
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi
script: 
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
os:
  - linux
compiler:
  - clang
  - gcc
notifications:
  email:
    on_success: change
    on_failure: always
